# Generated by Django 2.2.3 on 2019-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190708_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='题目')),
                ('category', models.CharField(max_length=20, verbose_name='分类')),
                ('limit', models.CharField(max_length=10, verbose_name='权限')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('introduce', models.CharField(max_length=90, verbose_name='介绍')),
                ('author', models.ForeignKey(on_delete='CASCADE', to='user.UserProfile')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
