# Generated by Django 2.2.3 on 2019-07-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='modify_time',
            new_name='modified_time',
        ),
    ]
