# Generated by Django 2.2.3 on 2019-07-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190708_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, verbose_name='留言')),
                ('created_time', models.DateTimeField(verbose_name='留言时间')),
                ('parent_comment', models.IntegerField(null=True, verbose_name='父留言')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('publisher_id', models.ForeignKey(on_delete='CASCADE', to='user.UserProfile')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
