# Generated by Django 2.2.3 on 2019-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190708_1516'),
        ('topic', '0002_auto_20190710_1149'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=60, verbose_name='留言')),
                ('created_time', models.DateTimeField(verbose_name='留言时间')),
                ('parent_comment', models.IntegerField(null=True, verbose_name='父留言')),
                ('publisher_id', models.ForeignKey(on_delete='CASCADE', to='user.UserProfile')),
                ('topic', models.ForeignKey(on_delete='CASCADE', to='topic.Topic')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
